/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <stdint.h>

#define GPIOA_ENABLE 		(1U << 0)
#define LED2_PIN 			(1U << 5)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHB1ENR |= GPIOA_ENABLE;

	// LED2 is pin PA_5
	GPIOA->MODER |=  (1U << 10);
	GPIOA->MODER &= ~(1U << 11);


	/* Loop forever */
	while (1) {
		GPIOA->ODR ^= LED2_PIN;
		for (int i = 0; i < 200000; i++) { ; }
	}
}
