/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include "debug_uart_driver.h"
#include <stdint.h>
#include <stdio.h>

#define GPIOA_ENABLE 		(1U << 0)
#define LED2_PIN 			(1U << 5)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#ifdef DEBUG
#define DEBUG_PRINT 		printf
#else
#define DEBUG_PRINT(...)
#endif



int main(void)
{

	debug_uart_init();

	// Clock to GPIO A, B, C
	RCC->AHB1ENR |=  (1U << 0 | 1U << 1 | 1U << 2);

	// Pin PA4 to output
	GPIOA->MODER |=  (1U << 8);
	GPIOA->MODER &= ~(1U << 9);

	// Pin PB0 to output
	GPIOB->MODER |=  (1U << 0);
	GPIOB->MODER &= ~(1U << 1);

	// Pins PC0, PC1 to output
	GPIOC->MODER |=  (1U << 0 | 1U << 2);
	GPIOC->MODER &= ~(1U << 1 | 1U << 3);

	int timer = 150000;

	while(1){
		// Order of lights to initialize, each should stay on for two cycles.

		GPIOC->ODR |=  (1U << 0); // PC0 on
		GPIOA->ODR &= ~(1U << 4); // PA4 off
		for (int i = 0; i < timer; i++) { ; } // Delay

		GPIOC->ODR |=  (1U << 1); // PC1 on
		GPIOC->ODR &= ~(1U << 0); // PC0 off
		for (int i = 0; i < timer; i++) { ; } // Delay

		GPIOB->ODR |=  (1U << 0); // PB0 on
		GPIOC->ODR &= ~(1U << 1); // PC1 off
		for (int i = 0; i < timer; i++) { ; } // Delay

		GPIOA->ODR |=  (1U << 4); // PA4 on
		GPIOB->ODR &= ~(1U << 0); // PB0 off
		for (int i = 0; i < timer; i++) { ; } // Delay
	}
}
